name: newmovie
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.7.2
  flutter: 
    sdk: flutter
  http: ^1.3.0
  internet_connection_checker: ^3.0.1
  lottie: ^3.2.0
  awesome_snackbar_content: ^0.1.0
  intl: ^0.19.0

dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

